"""empty message

Revision ID: 3f3d4b9a7cd4
Revises: None
Create Date: 2014-08-19 10:06:18.009970

"""

# revision identifiers, used by Alembic.
revision = '3f3d4b9a7cd4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'author_id')
    ### end Alembic commands ###
